export const dashboardActionTypes = {
  FETCH_REQUEST: "FETCH_REQUEST",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_FAILURE: "FETCH_FAILURE",
  STATUS_REQUEST: "STATUS_REQUEST",
  STATUS_SUCCESS: "STATUS_SUCCESS",
  STATUS_FAILURE: "STATUS_FAILURE",
};
